# Generated by Django 4.1.3 on 2023-01-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Replacement_Reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reverves_Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.years')),
            ],
        ),
        migrations.CreateModel(
            name='Common_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_expenses_dues', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('revenues', models.IntegerField()),
                ('minus_delinquent_payments', models.IntegerField()),
                ('gross_profit', models.IntegerField()),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.years')),
            ],
        ),
    ]
